name: run bot

on:
  schedule:
    - cron: 30 8 * * 0
  workflow_dispatch:
    inputs:
    
jobs:
  sync:
    runs-on: ubuntu-latest
    name: tgbot

    steps:
      - uses: actions/checkout@v2
      - name: Bot Install
        run: |
          git clone https://github.com/roshanconnor123/Fclone_Tg_Bot
          cd Fclone_Tg_Bot
          pip3 install -r requirements.txt
          cat >  telegram_gcloner/config.ini  << EOF
          ${{ secrets.BOT_CONFIG }}
          EOF
          sudo chmod +x fclone
          sudo chmod +x telegram_gcloner/telegram_gcloner.py
          sudo python3 telegram_gcloner/telegram_gcloner.py
  sync2:
    needs : sync
    runs-on: ubuntu-latest
    name: tgbot2

    steps:
      - uses: actions/checkout@v2
      - name: Bot Install2
        run: |
          git clone https://github.com/crypt-bphc/Fclone_Tg_Bot
          cd Fclone_Tg_Bot
          pip3 install -r requirements.txt
          cat >  telegram_gcloner/config.ini  << EOF
          ${{ secrets.BOT_CONFIG }}
          EOF
          sudo chmod +x fclone
          sudo chmod +x telegram_gcloner/telegram_gcloner.py
          sudo python3 telegram_gcloner/telegram_gcloner.py


