name: run bot

on:
  schedule:
    - cron: 0 11 * * *
  workflow_dispatch:
    inputs:
    
jobs:
  sync1:
    runs-on: ubuntu-latest
    name: tgbot1

    steps:
      - uses: actions/checkout@v2
      - name: Bot Install1
        run: |
          git clone https://github.com/crypt-bphc/Fclone_Tg_Bot
          cd Fclone_Tg_Bot
          pip3 install -r requirements.txt
          cat >  telegram_gcloner/config.ini  << EOF
          ${{ secrets.BOT_CONFIG }}
          EOF
          sudo chmod +x fclone
          sudo chmod +x telegram_gcloner/telegram_gcloner.py
          sudo python3 telegram_gcloner/telegram_gcloner.py
  sync2:
    needs : sync1
    runs-on: ubuntu-latest
    name: tgbot2

    steps:
      - uses: actions/checkout@v2
      - name: Bot Install2
        run: |
          git clone https://github.com/crypt-bphc/Fclone_Tg_Bot
          cd Fclone_Tg_Bot
          pip3 install -r requirements.txt
          cat >  telegram_gcloner/config.ini  << EOF
          ${{ secrets.BOT_CONFIG }}
          EOF
          sudo chmod +x fclone
          sudo chmod +x telegram_gcloner/telegram_gcloner.py
          sudo python3 telegram_gcloner/telegram_gcloner.py
  sync3:
    needs : sync2
    runs-on: ubuntu-latest
    name: tgbot3

    steps:
      - uses: actions/checkout@v2
      - name: Bot Install3
        run: |
          git clone https://github.com/crypt-bphc/Fclone_Tg_Bot
          cd Fclone_Tg_Bot
          pip3 install -r requirements.txt
          cat >  telegram_gcloner/config.ini  << EOF
          ${{ secrets.BOT_CONFIG }}
          EOF
          sudo chmod +x fclone
          sudo chmod +x telegram_gcloner/telegram_gcloner.py
          sudo python3 telegram_gcloner/telegram_gcloner.py
  sync4:
    needs : sync3
    runs-on: ubuntu-latest
    name: tgbot4

    steps:
      - uses: actions/checkout@v2
      - name: Bot Install4
        run: |
          git clone https://github.com/crypt-bphc/Fclone_Tg_Bot
          cd Fclone_Tg_Bot
          pip3 install -r requirements.txt
          cat >  telegram_gcloner/config.ini  << EOF
          ${{ secrets.BOT_CONFIG }}
          EOF
          sudo chmod +x fclone
          sudo chmod +x telegram_gcloner/telegram_gcloner.py
          sudo python3 telegram_gcloner/telegram_gcloner.py 
